@extends('layouts.app')

@section('title', 'Verify Device')

@section('content')
    <div class="min-h-screen flex items-center justify-center px-4 py-12">
        <div class="w-full max-w-md rounded-2xl p-8 shadow-2xl card-backdrop">
            <h2 class="text-2xl font-bold text-center mb-2">Verify your device</h2>
            <p class="text-center text-sm text-white/70 mb-6">Enter the 6-digit code generated by the app for this device.</p>


            @if (session('verification_code_debug'))
                <div class="mb-4 p-3 rounded-lg bg-blue-500/10 border border-blue-500/25 text-sm text-blue-200">
                    <p class="font-semibold">Device verification code:</p>
                    <p class="break-all">{{ session('verification_code_debug') }}</p>
                </div>
            @endif

            @if ($errors->any())
                <div class="mb-4 p-3 rounded-lg bg-red-500/10 border border-red-500/20">
                    <ul class="text-sm text-red-400">
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form method="POST" action="{{ route('verification.device.verify') }}" id="verifyDeviceForm">
                @csrf
                <input type="hidden" name="device_id" id="verifyDeviceId" value="">

                <div class="mb-4">
                    <label class="block text-sm text-white/70 mb-2">Verification Code</label>
                    <input
                        type="text"
                        name="verification_code"
                        value="{{ old('verification_code') }}"
                        maxlength="6"
                        pattern="[0-9]{6}"
                        placeholder="Enter 6-digit code"
                        required
                        class="w-full px-4 py-3 rounded-lg bg-white/5 border border-white/6 text-white placeholder-white/60 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    >
                </div>

                <div class="mb-4">
                    <button type="submit" class="inline-block bg-gradient-to-b from-blue-500 to-blue-800 text-white font-bold py-3 px-6 rounded-xl shadow-lg">Verify Device</button>
                </div>
            </form>

            <div class="mt-4 text-sm text-white/75">
                <a href="{{ route('login') }}" class="underline">Back to login</a>
            </div>
        </div>
    </div>

    <script>
        (function () {
            const key = 'attendance_device_id';
            let deviceId = localStorage.getItem(key);

            if (!deviceId) {
                deviceId = (window.crypto && window.crypto.randomUUID)
                    ? window.crypto.randomUUID()
                    : 'dev-' + Math.random().toString(36).slice(2) + Date.now();
                localStorage.setItem(key, deviceId);
            }

            const deviceField = document.getElementById('verifyDeviceId');
            if (deviceField) {
                deviceField.value = deviceId;
            }
        })();
    </script>
@endsection
